output_dir: ./outputs
leaderboard_json: ./outputs/nanobeir_leaderboard.json

datasets: ["scifact"]   # add "fiqa", "scidocs" later if you want

cost_per_1k:
  qwen_edge_llamaserver: 0.02

models:
  qwen_edge_llamaserver:
    endpoint: http://127.0.0.1:8000/embed
  # baseline:
  #   hf_id: sentence-transformers/all-MiniLM-L6-v2
